version: '3.9'

services:

    app:
        container_name: 'back'
        build:
            context: .
        ports:
            - ${PORT}:${DOCKER_PORT}
        restart: always
        volumes:
            - .:/home/app
        command: bash -c "npm install && npm run dev"
