version: '3.9'

services:
    app:
        container_name: 'back'
        build:
            context: .
        ports:
            - 0.0.0.0:${PORT}:${DOCKER_PORT}
        restart: always
        volumes:
            - .:/app
networks:
    default:
        external:
            name: ${NETWORK}
